// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using horse_kurs.Models;

#nullable disable

namespace horse_kurs.Migrations
{
    [DbContext(typeof(EquestrianClubContext))]
    [Migration("20260402095452_SyncModelsAndData")]
    partial class SyncModelsAndData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("horse_kurs.Models.Arena", b =>
                {
                    b.Property<int>("IdArena")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_Arena");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdArena"));

                    b.Property<string>("Coverage")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<decimal>("Length")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Доступен");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<decimal>("Width")
                        .HasColumnType("decimal(5, 2)");

                    b.HasKey("IdArena")
                        .HasName("PK__Arena__D120353F116F169D");

                    b.ToTable("Arena", (string)null);
                });

            modelBuilder.Entity("horse_kurs.Models.Client", b =>
                {
                    b.Property<int>("IdClient")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_Client");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdClient"));

                    b.Property<decimal>("Balance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(10, 2)")
                        .HasDefaultValueSql("((0.00))");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("Date_of_birth");

                    b.Property<DateOnly>("DateOfRegistration")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasColumnName("Date_of_registration")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Flat")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("House")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("LevelOfTraining")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Новичок")
                        .HasColumnName("Level_of_training");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Passport")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Patronymic")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdClient")
                        .HasName("PK__Client__B5AE4EC8092BAF53");

                    b.HasIndex(new[] { "Passport" }, "UQ_Client_Passport")
                        .IsUnique();

                    b.HasIndex(new[] { "Phone" }, "UQ_Client_Phone")
                        .IsUnique();

                    b.ToTable("Client", (string)null);
                });

            modelBuilder.Entity("horse_kurs.Models.Coach", b =>
                {
                    b.Property<int>("IdCoach")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_Coach");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCoach"));

                    b.Property<int?>("IdEmployee")
                        .HasColumnType("int")
                        .HasColumnName("ID_Employee");

                    b.Property<string>("Qualification")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Specialization")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdCoach")
                        .HasName("PK__Coach__6D1B22C4B2E492B3");

                    b.HasIndex("IdEmployee");

                    b.ToTable("Coach", (string)null);
                });

            modelBuilder.Entity("horse_kurs.Models.Competition", b =>
                {
                    b.Property<int>("IdCompetition")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_Competition");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCompetition"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("IdArena")
                        .HasColumnType("int")
                        .HasColumnName("ID_Arena");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Запланировано");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("IdCompetition")
                        .HasName("PK__Competit__0E2B371D020CE323");

                    b.HasIndex("IdArena");

                    b.ToTable("Competition", (string)null);
                });

            modelBuilder.Entity("horse_kurs.Models.Employee", b =>
                {
                    b.Property<int>("IdEmployee")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_Employee");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEmployee"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("Date_of_birth");

                    b.Property<string>("FlatNumber")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("Flat_number");

                    b.Property<string>("HouseNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("House_number");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Patronymic")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Post")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdEmployee")
                        .HasName("PK__Employee__D9EE4F36F60984C0");

                    b.ToTable("Employee", (string)null);
                });

            modelBuilder.Entity("horse_kurs.Models.Horse", b =>
                {
                    b.Property<int>("IdHorse")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_Horse");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdHorse"));

                    b.Property<string>("Breed")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("Date_of_birth");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int?>("IdStall")
                        .HasColumnType("int")
                        .HasColumnName("ID_Stall");

                    b.Property<string>("LevelOfTraining")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Начинающий")
                        .HasColumnName("Level_of_training");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Passport")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("StateOfHealth")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Здорова")
                        .HasColumnName("State_of_health");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("В работе");

                    b.HasKey("IdHorse")
                        .HasName("PK__Horse__1F05AB7CD385EE49");

                    b.HasIndex("IdStall");

                    b.HasIndex(new[] { "Passport" }, "UQ_Horse_Passport")
                        .IsUnique();

                    b.ToTable("Horse", (string)null);
                });

            modelBuilder.Entity("horse_kurs.Models.Lesson", b =>
                {
                    b.Property<int>("IdLesson")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_Lesson");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdLesson"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int?>("IdArena")
                        .HasColumnType("int")
                        .HasColumnName("ID_Arena");

                    b.Property<int>("IdClient")
                        .HasColumnType("int")
                        .HasColumnName("ID_Client");

                    b.Property<int>("IdCoach")
                        .HasColumnType("int")
                        .HasColumnName("ID_Coach");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("IdLesson")
                        .HasName("PK__Lesson__67381F3BE8AF0538");

                    b.HasIndex("IdArena");

                    b.HasIndex("IdClient");

                    b.HasIndex("IdCoach");

                    b.ToTable("Lesson", (string)null);
                });

            modelBuilder.Entity("horse_kurs.Models.LessonHorse", b =>
                {
                    b.Property<int>("IdLessonHorse")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_Lesson_Horse");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdLessonHorse"));

                    b.Property<int>("IdHorse")
                        .HasColumnType("int")
                        .HasColumnName("ID_Horse");

                    b.Property<int>("IdLesson")
                        .HasColumnType("int")
                        .HasColumnName("ID_Lesson");

                    b.HasKey("IdLessonHorse")
                        .HasName("PK__Lesson_H__B12E82A70E548177");

                    b.HasIndex("IdHorse");

                    b.HasIndex("IdLesson");

                    b.ToTable("Lesson_Horse", (string)null);
                });

            modelBuilder.Entity("horse_kurs.Models.Membership", b =>
                {
                    b.Property<int>("IdMembership")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_Membership");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMembership"));

                    b.Property<int>("IdClient")
                        .HasColumnType("int")
                        .HasColumnName("ID_Client");

                    b.Property<int>("LessonsTotal")
                        .HasColumnType("int")
                        .HasColumnName("Lessons_Total");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<DateOnly>("PurchaseDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasColumnName("Purchase_Date")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Активен");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateOnly>("ValidFrom")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasColumnName("Valid_From")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateOnly>("ValidUntil")
                        .HasColumnType("date")
                        .HasColumnName("Valid_Until");

                    b.HasKey("IdMembership")
                        .HasName("PK__Membersh__49C2410B360EE594");

                    b.HasIndex("IdClient");

                    b.ToTable("Membership", (string)null);
                });

            modelBuilder.Entity("horse_kurs.Models.MembershipLesson", b =>
                {
                    b.Property<int>("IdMembershipLesson")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_Membership_Lesson");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMembershipLesson"));

                    b.Property<int>("IdLesson")
                        .HasColumnType("int")
                        .HasColumnName("ID_Lesson");

                    b.Property<int>("IdMembership")
                        .HasColumnType("int")
                        .HasColumnName("ID_Membership");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("IdMembershipLesson")
                        .HasName("PK__Membersh__47838CC859C675E3");

                    b.HasIndex("IdLesson");

                    b.HasIndex("IdMembership");

                    b.ToTable("Membership_Lesson", (string)null);
                });

            modelBuilder.Entity("horse_kurs.Models.Participation", b =>
                {
                    b.Property<int>("IdParticipation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_Participation");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdParticipation"));

                    b.Property<int>("IdClient")
                        .HasColumnType("int")
                        .HasColumnName("ID_Client");

                    b.Property<int>("IdCompetition")
                        .HasColumnType("int")
                        .HasColumnName("ID_Competition");

                    b.Property<int>("IdHorse")
                        .HasColumnType("int")
                        .HasColumnName("ID_Horse");

                    b.Property<DateOnly>("RegistrationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasColumnName("Registration_date")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("ResultPlace")
                        .HasColumnType("int")
                        .HasColumnName("Result_place");

                    b.Property<decimal?>("Score")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<int?>("StartNumber")
                        .HasColumnType("int")
                        .HasColumnName("Start_number");

                    b.HasKey("IdParticipation")
                        .HasName("PK__Particip__1A686438E5E30A85");

                    b.HasIndex("IdClient");

                    b.HasIndex("IdHorse");

                    b.HasIndex(new[] { "IdCompetition", "StartNumber" }, "UQ_Participation_StartNumber")
                        .IsUnique()
                        .HasFilter("[Start_number] IS NOT NULL");

                    b.ToTable("Participation", (string)null);
                });

            modelBuilder.Entity("horse_kurs.Models.Payment", b =>
                {
                    b.Property<int>("IdPayment")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_Payment");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPayment"));

                    b.Property<int?>("IdCompetition")
                        .HasColumnType("int")
                        .HasColumnName("ID_Competition");

                    b.Property<int?>("IdLesson")
                        .HasColumnType("int")
                        .HasColumnName("ID_Lesson");

                    b.Property<int?>("IdMembership")
                        .HasColumnType("int")
                        .HasColumnName("ID_Membership");

                    b.Property<string>("MethodPaid")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Method_paid");

                    b.Property<DateTime>("PaymentDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("Payment_date")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Завершено");

                    b.Property<decimal>("Summa")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("IdPayment")
                        .HasName("PK__Payment__C2118ADEDA806726");

                    b.HasIndex("IdCompetition");

                    b.HasIndex("IdLesson");

                    b.HasIndex("IdMembership");

                    b.ToTable("Payment", (string)null);
                });

            modelBuilder.Entity("horse_kurs.Models.ScheduleArena", b =>
                {
                    b.Property<int>("IdSchedule")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_Schedule");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSchedule"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time")
                        .HasColumnName("End_time");

                    b.Property<int>("IdArena")
                        .HasColumnType("int")
                        .HasColumnName("ID_Arena");

                    b.Property<int?>("IdCompetition")
                        .HasColumnType("int")
                        .HasColumnName("ID_Competition");

                    b.Property<int?>("IdLesson")
                        .HasColumnType("int")
                        .HasColumnName("ID_Lesson");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time")
                        .HasColumnName("Start_time");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Запланировано");

                    b.HasKey("IdSchedule")
                        .HasName("PK__Schedule__73616218C0A1A969");

                    b.HasIndex("IdArena");

                    b.HasIndex("IdCompetition");

                    b.HasIndex("IdLesson");

                    b.ToTable("Schedule_Arena", (string)null);
                });

            modelBuilder.Entity("horse_kurs.Models.Stall", b =>
                {
                    b.Property<int>("IdStall")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_Stall");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdStall"));

                    b.Property<int?>("IdEmployee")
                        .HasColumnType("int")
                        .HasColumnName("ID_Employee");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal>("Size")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Свободен");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("IdStall")
                        .HasName("PK__Stall__922B9F5F83530074");

                    b.HasIndex("IdEmployee");

                    b.HasIndex(new[] { "Number" }, "UQ_Stall_Number")
                        .IsUnique();

                    b.ToTable("Stall", (string)null);
                });

            modelBuilder.Entity("horse_kurs.Models.Users", b =>
                {
                    b.Property<int>("IdUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUser"));

                    b.Property<int?>("ClientIdClient")
                        .HasColumnType("int");

                    b.Property<int?>("IdClient")
                        .HasColumnType("int");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdUser");

                    b.HasIndex("ClientIdClient");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("horse_kurs.Models.Coach", b =>
                {
                    b.HasOne("horse_kurs.Models.Employee", "IdEmployeeNavigation")
                        .WithMany("Coaches")
                        .HasForeignKey("IdEmployee")
                        .HasConstraintName("FK_Coach_Employee");

                    b.Navigation("IdEmployeeNavigation");
                });

            modelBuilder.Entity("horse_kurs.Models.Competition", b =>
                {
                    b.HasOne("horse_kurs.Models.Arena", "IdArenaNavigation")
                        .WithMany("Competitions")
                        .HasForeignKey("IdArena")
                        .IsRequired()
                        .HasConstraintName("FK_Competition_Arena");

                    b.Navigation("IdArenaNavigation");
                });

            modelBuilder.Entity("horse_kurs.Models.Horse", b =>
                {
                    b.HasOne("horse_kurs.Models.Stall", "IdStallNavigation")
                        .WithMany("Horses")
                        .HasForeignKey("IdStall")
                        .HasConstraintName("FK_Horse_Stall");

                    b.Navigation("IdStallNavigation");
                });

            modelBuilder.Entity("horse_kurs.Models.Lesson", b =>
                {
                    b.HasOne("horse_kurs.Models.Arena", "IdArenaNavigation")
                        .WithMany("Lessons")
                        .HasForeignKey("IdArena")
                        .HasConstraintName("FK_Lesson_Arena");

                    b.HasOne("horse_kurs.Models.Client", "IdClientNavigation")
                        .WithMany("Lessons")
                        .HasForeignKey("IdClient")
                        .IsRequired()
                        .HasConstraintName("FK_Lesson_Client");

                    b.HasOne("horse_kurs.Models.Coach", "IdCoachNavigation")
                        .WithMany("Lessons")
                        .HasForeignKey("IdCoach")
                        .IsRequired()
                        .HasConstraintName("FK_Lesson_Coach");

                    b.Navigation("IdArenaNavigation");

                    b.Navigation("IdClientNavigation");

                    b.Navigation("IdCoachNavigation");
                });

            modelBuilder.Entity("horse_kurs.Models.LessonHorse", b =>
                {
                    b.HasOne("horse_kurs.Models.Horse", "IdHorseNavigation")
                        .WithMany("LessonHorses")
                        .HasForeignKey("IdHorse")
                        .IsRequired()
                        .HasConstraintName("FK_LessonHorse_Horse");

                    b.HasOne("horse_kurs.Models.Lesson", "IdLessonNavigation")
                        .WithMany("LessonHorses")
                        .HasForeignKey("IdLesson")
                        .IsRequired()
                        .HasConstraintName("FK_LessonHorse_Lesson");

                    b.Navigation("IdHorseNavigation");

                    b.Navigation("IdLessonNavigation");
                });

            modelBuilder.Entity("horse_kurs.Models.Membership", b =>
                {
                    b.HasOne("horse_kurs.Models.Client", "IdClientNavigation")
                        .WithMany("Memberships")
                        .HasForeignKey("IdClient")
                        .IsRequired()
                        .HasConstraintName("FK_Membership_Client");

                    b.Navigation("IdClientNavigation");
                });

            modelBuilder.Entity("horse_kurs.Models.MembershipLesson", b =>
                {
                    b.HasOne("horse_kurs.Models.Lesson", "IdLessonNavigation")
                        .WithMany("MembershipLessons")
                        .HasForeignKey("IdLesson")
                        .IsRequired()
                        .HasConstraintName("FK_MembershipLesson_Lesson");

                    b.HasOne("horse_kurs.Models.Membership", "IdMembershipNavigation")
                        .WithMany("MembershipLessons")
                        .HasForeignKey("IdMembership")
                        .IsRequired()
                        .HasConstraintName("FK_MembershipLesson_Membership");

                    b.Navigation("IdLessonNavigation");

                    b.Navigation("IdMembershipNavigation");
                });

            modelBuilder.Entity("horse_kurs.Models.Participation", b =>
                {
                    b.HasOne("horse_kurs.Models.Client", "IdClientNavigation")
                        .WithMany("Participations")
                        .HasForeignKey("IdClient")
                        .IsRequired()
                        .HasConstraintName("FK_Participation_Client");

                    b.HasOne("horse_kurs.Models.Competition", "IdCompetitionNavigation")
                        .WithMany("Participations")
                        .HasForeignKey("IdCompetition")
                        .IsRequired()
                        .HasConstraintName("FK_Participation_Competition");

                    b.HasOne("horse_kurs.Models.Horse", "IdHorseNavigation")
                        .WithMany("Participations")
                        .HasForeignKey("IdHorse")
                        .IsRequired()
                        .HasConstraintName("FK_Participation_Horse");

                    b.Navigation("IdClientNavigation");

                    b.Navigation("IdCompetitionNavigation");

                    b.Navigation("IdHorseNavigation");
                });

            modelBuilder.Entity("horse_kurs.Models.Payment", b =>
                {
                    b.HasOne("horse_kurs.Models.Competition", "IdCompetitionNavigation")
                        .WithMany("Payments")
                        .HasForeignKey("IdCompetition")
                        .HasConstraintName("FK_Payment_Competition");

                    b.HasOne("horse_kurs.Models.Lesson", "IdLessonNavigation")
                        .WithMany("Payments")
                        .HasForeignKey("IdLesson")
                        .HasConstraintName("FK_Payment_Lesson");

                    b.HasOne("horse_kurs.Models.Membership", "IdMembershipNavigation")
                        .WithMany("Payments")
                        .HasForeignKey("IdMembership")
                        .HasConstraintName("FK_Payment_Membership");

                    b.Navigation("IdCompetitionNavigation");

                    b.Navigation("IdLessonNavigation");

                    b.Navigation("IdMembershipNavigation");
                });

            modelBuilder.Entity("horse_kurs.Models.ScheduleArena", b =>
                {
                    b.HasOne("horse_kurs.Models.Arena", "IdArenaNavigation")
                        .WithMany("ScheduleArenas")
                        .HasForeignKey("IdArena")
                        .IsRequired()
                        .HasConstraintName("FK_Schedule_Arena");

                    b.HasOne("horse_kurs.Models.Competition", "IdCompetitionNavigation")
                        .WithMany("ScheduleArenas")
                        .HasForeignKey("IdCompetition")
                        .HasConstraintName("FK_Schedule_Competition");

                    b.HasOne("horse_kurs.Models.Lesson", "IdLessonNavigation")
                        .WithMany("ScheduleArenas")
                        .HasForeignKey("IdLesson")
                        .HasConstraintName("FK_Schedule_Lesson");

                    b.Navigation("IdArenaNavigation");

                    b.Navigation("IdCompetitionNavigation");

                    b.Navigation("IdLessonNavigation");
                });

            modelBuilder.Entity("horse_kurs.Models.Stall", b =>
                {
                    b.HasOne("horse_kurs.Models.Employee", "IdEmployeeNavigation")
                        .WithMany("Stalls")
                        .HasForeignKey("IdEmployee")
                        .HasConstraintName("FK_Stall_Employee");

                    b.Navigation("IdEmployeeNavigation");
                });

            modelBuilder.Entity("horse_kurs.Models.Users", b =>
                {
                    b.HasOne("horse_kurs.Models.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientIdClient");

                    b.Navigation("Client");
                });

            modelBuilder.Entity("horse_kurs.Models.Arena", b =>
                {
                    b.Navigation("Competitions");

                    b.Navigation("Lessons");

                    b.Navigation("ScheduleArenas");
                });

            modelBuilder.Entity("horse_kurs.Models.Client", b =>
                {
                    b.Navigation("Lessons");

                    b.Navigation("Memberships");

                    b.Navigation("Participations");
                });

            modelBuilder.Entity("horse_kurs.Models.Coach", b =>
                {
                    b.Navigation("Lessons");
                });

            modelBuilder.Entity("horse_kurs.Models.Competition", b =>
                {
                    b.Navigation("Participations");

                    b.Navigation("Payments");

                    b.Navigation("ScheduleArenas");
                });

            modelBuilder.Entity("horse_kurs.Models.Employee", b =>
                {
                    b.Navigation("Coaches");

                    b.Navigation("Stalls");
                });

            modelBuilder.Entity("horse_kurs.Models.Horse", b =>
                {
                    b.Navigation("LessonHorses");

                    b.Navigation("Participations");
                });

            modelBuilder.Entity("horse_kurs.Models.Lesson", b =>
                {
                    b.Navigation("LessonHorses");

                    b.Navigation("MembershipLessons");

                    b.Navigation("Payments");

                    b.Navigation("ScheduleArenas");
                });

            modelBuilder.Entity("horse_kurs.Models.Membership", b =>
                {
                    b.Navigation("MembershipLessons");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("horse_kurs.Models.Stall", b =>
                {
                    b.Navigation("Horses");
                });
#pragma warning restore 612, 618
        }
    }
}
